const players = [
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
]

export default players;