const defaultPlayers = [
  {
    age: 42, 
    birth_country: "Italy",
    birth_date: "28/01/1978",
    birth_place: "Carrara",
    firstname: "Gianluigi",
    height: "192 cm",
    lastname: "Buffon",
    nationality: "Italy",
    number: null,
    player_id: 254,
    player_name: "G. Buffon",
    position: "Goalkeeper",
    weight: "92 kg"
  },
  {
    age: 28, 
    birth_country: "Italy",
    birth_date: "20/10/1992",
    birth_place: "Milano",
    firstname: "Mattia",
    height: "182 cm",
    lastname: "De Sciglio",
    nationality: "Italy",
    number: null,
    player_id: 858,
    player_name: "M. De Sciglio",
    position: "Defender",
    weight: "78 kg"
  },
  
  {
    age: 36,
    birth_country: "Italy",
    birth_date: "14/08/1984",
    birth_place: "Pisa",
    firstname: "Giorgio",
    height: "187 cm",
    lastname: "Chiellini",
    nationality: "Italy",
    number: null,
    player_id: 856,
    player_name: "Giorgio Chiellini",
    position: "Defender",
    weight: "85 kg",
  },
  {
    age: 33,
    birth_country: "Italy",
    birth_date: "01/05/1987",
    birth_place: "Viterbo",
    firstname: "Leonardo",
    height: "190 cm",
    lastname: "Bonucci",
    nationality: "Italy",
    number: null,
    player_id: 853,
    player_name: "L. Bonucci",
    position: "Defender",
    weight: "85 kg"
  },
  {
    age: 22,
    birth_country: "Spain",
    birth_date: "04/11/1998",
    birth_place: "Madrid",
    firstname: "Achraf",
    height: "181 cm",
    lastname: "Hakimi Mouh",
    nationality: "Morocco",
    number: null,
    player_id: 9,
    player_name: "Achraf Hakimi Mouh",
    position: "Defender",
    weight: "73 kg"
  },
  {
    age: 20,
    birth_country: "Sweden",
    birth_date: "25/04/2000",
    birth_place: null,
    firstname: "Dejan",
    height: "186 cm",
    lastname: "Kulusevski",
    nationality: "Sweden",
    number: null,
    player_id: 30435,
    player_name: "D. Kulusevski",
    position: "Midfielder",
    weight: null
  },
  {
    age: 23,
    birth_country: "Uruguay",
    birth_date: "25/06/1997",
    birth_place: "Nueva Helvecia",
    firstname: "Rodrigo",
    height: "187 cm",
    lastname: "Bentancur Colmán",
    nationality: "Uruguay",
    number: null,
    player_id: 863,
    player_name: "Rodrigo Bentancur Colmán",
    position: "Midfielder",
    weight: "72 kg"
  },
  {
    age: 22,
    birth_country: "USA",
    birth_date: "28/08/1998",
    birth_place: "Little Elm",
    firstname: "Weston",
    height: "185 cm",
    lastname: "McKennie",
    nationality: "USA",
    number: null,
    player_id: 415,
    player_name: "W. McKennie",
    position: "Midfielder",
    weight: "84 kg"
  },
  {
    age: 27,
    birth_country: "Argentina",
    birth_date: "15/11/1993",
    birth_place: "Laguna Larga",
    firstname: "Paulo Bruno",
    height: "177 cm",
    lastname: "Exequiel Dybala",
    nationality: "Argentina",
    number: null,
    player_id: 875,
    player_name: "Paulo Bruno Exequiel Dybala",
    position: "Attacker",
    weight: "75 kg"
  },
  {
    age: 45,
    birth_country: "Poland",
    birth_date: "27/06/1974",
    birth_place: null,
    firstname: "Robert",
    height: null,
    lastname: "Lewandowski",
    nationality: "Poland",
    number: null,
    player_id: 147229,
    player_name: "Robert Lewandowski",
    position: "Attacker",
    weight: null
  },
  {
    age: 35, 
    birth_country: "Portugal",
    birth_date: "05/02/1985",
    birth_place: "Funchal",
    firstname: "Cristiano Ronaldo",
    height: "187 cm",
    lastname: "dos Santos Aveiro",
    nationality: "Portugal",
    number: null,
    player_id: 874,
    player_name: "Cristiano Ronaldo",
    position: "Attacker",
    weight: "83 kg"
  },
]

export default defaultPlayers
